### ISSUE TITLE
SentinelAPI credentials problem

### ISSUE THREAD

**Issue by nielsjk** [sentinelsat/sentinelsat#499]
In a script that uses the SentinelAPI module, and which has worked for years, I now get this message when executing:

```
__File "/home/njk/anaconda3/lib/python3.7/site-packages/sentinelsat/sentinel.py", line 1320, in _check_scihub_response
    raise api_error_

SentinelAPIError: # HTTP Status 401 – Unauthorized_

* * *

 **Type** Status Report

 **Message** Unauthorized

 **Description** The request has not been applied because it lacks valid
authentication credentials for the target resource.

* * *

_### Apache Tomcat/8.0.53_
```

I have checked the credentials and they should be ok, so what is up here?

**Comment by j08lue** [comment]
Our upstream endpoint is not exactly stable. Which version of Sentinelsat are you using?

**Comment by fpl** [comment]
I found the same issue with the Debian Buster (10) distributed version of sentinelsat (0.12.2). Solved by simply upgrading to the current version via pip.

**Comment by nielsjk** [comment]
I am running it on Ubuntu 18.04  (on a Oracle VM VirtualBox). 

Conda list returns:

sentinelsat               0.14                     pypi_0    pypi

I try to re-install:

conda install -c conda-forge sentinelsat

then Conda list again:

sentinelsat               0.14                     pypi_0    pypi

Has anything changed when trying to use sentinelapi ? Yes now I get the same error just with a new error description:

_UnauthorizedError: Invalid user name or password. Note that account creation and password changes may take up to a week to propagate to the 'https://apihub.copernicus.eu/apihub/' API URL you are using. Consider switching to 'https://scihub.copernicus.eu/dhus/' instead in the mean time._

**Comment by j08lue** [comment]
`pip install --upgrade sentinelsat`

**Comment by nielsjk** [comment]
> pip install --upgrade sentinelsat

No luck with this. still the same problem. Also still Sentinelsat 0.14 when listed.

**Comment by fpl** [comment]
Could be overridden by a system global version. You can try apt remove sentinelsat, or even remove the sentinelsat dir in the global path (e.g. /usr/lib/python3/dist-packages/sentinelsat)

**Comment by j08lue** [comment]
The way to control which distribution a package gets installed into is to call `python -m pip install --upgrade sentinelsat`, `python3 -m pip install ...`, `/path/to/my/python -m pip install ...`.

You could also start using virtual environments to have more control on where packages are loaded from.

**Comment by lukas-schmidt78383** [comment]
You can also try to override the default api url yourself:
```
api = sentinelsat.SentinelAPI(username, password, 'https://apihub.copernicus.eu/apihub')
```
or 
```
api = sentinelsat.SentinelAPI(username, password, 'https://scihub.copernicus.eu/dhus/')`
```

* `https://apihub.copernicus.eu/apihub` is the new default api url (v1.0.1)
* `https://scihub.copernicus.eu/apihub/` was the default url from the old version (seen in 0.13) (does not seem to work anymore) 
* `https://scihub.copernicus.eu/dhus/`  is usually used for interactive web queries but should work as well
